# Generated by Django 6.0.1 on 2026-01-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gifts",
            name="guest_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="gifts",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
