# Generated by Django 6.0.1 on 2026-01-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0002_gifts_guest_name_gifts_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gifts",
            name="image_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
